type TitleMapping = {
  [key: string]: any | Record<any, any>
}

const originalMapping: TitleMapping = {
    version: "Version",
    status_code: "Status Code",
    status_message: "Status Message",
    time: "Response Time",
    cost: "Cost",
    tasks_count: "Task Count",
    tasks_error: "Task Error Count",
    id: "Task ID",
    crawl_progress: "Crawl Progress",
    max_crawl_pages: "Max Crawl Pages",
    pages_in_queue: "Pages in Queue",
    pages_crawled: "Pages Crawled",
    crawl_gateway_address: "Crawl Gateway Address",
    domain_info: "Domain Info",
    name: "Domain Name",
    cms: "Content Management System (CMS)",
    ip: "IP Address",
    server: "Web Server",
    crawl_start: "Crawl Start Time",
    crawl_end: "Crawl End Time",
    extended_crawl_status: "Extended Crawl Status",
    ssl_info: "SSL Certificate Info",
    valid_certificate: "Valid SSL Certificate",
    certificate_issuer: "SSL Certificate Issuer",
    certificate_subject: "SSL Certificate Subject",
    certificate_version: "SSL Certificate Version",
    certificate_hash: "SSL Certificate Hash",
    certificate_expiration_date: "SSL Certificate Expiration Date",
    checks: "Checks",
    sitemap: "Has Sitemap",
    robots_txt: "Has robots.txt File",
    total_pages: "Total Pages",
    links_external: "External Links",
    links_internal: "Internal Links",
    duplicate_title: "Duplicate Titles",
    duplicate_description: "Duplicate Descriptions",
    duplicate_content: "Duplicate Content",
    broken_links: "Broken Links",
    onpage_score: "On-Page Score",
    non_indexable: "Non-Indexable",
    canonical: "Canonical URLs",
    duplicate_meta_tags: "Duplicate Meta Tags",
    no_description: "Pages with No Description",
    frame: "Frames",
    large_page_size: "Large Page Size",
    irrelevant_description: "Irrelevant Description",
    irrelevant_meta_keywords: "Irrelevant Meta Keywords",
    is_https: "Uses HTTPS",
    is_http: "Uses HTTP",
    title_too_long: "Title Too Long",
    low_content_rate: "Low Content Rate",
    small_page_size: "Small Page Size",
    no_h1_tag: "No H1 Tag",
    recursive_canonical: "Recursive Canonical URLs",
    no_favicon: "No Favicon",
    no_image_alt: "Images Missing Alt Text",
    no_image_title: "Images Missing Title Text",
    seo_friendly_url: "SEO-Friendly URL",
    seo_friendly_url_characters_check: "SEO-Friendly URL (Character Check)",
    seo_friendly_url_dynamic_check: "SEO-Friendly URL (Dynamic Check)",
    seo_friendly_url_keywords_check: "SEO-Friendly URL (Keywords Check)",
    seo_friendly_url_relative_length_check: "SEO-Friendly URL (Relative Length Check)",
    title_too_short: "Title Too Short",
    no_content_encoding: "No Content Encoding",
    high_waiting_time: "High Waiting Time",
    high_loading_time: "High Loading Time",
    is_redirect: "Is a Redirect",
    is_broken: "Is Broken",
    is_4xx_code: "Is a 4xx Code",
    is_5xx_code: "Is a 5xx Code",
    is_www: "Has 'www' Prefix",
    no_doctype: "No Document Type (DOCTYPE)",
    no_encoding_meta_tag: "No Encoding Meta Tag",
    high_content_rate: "High Content Rate",
    low_character_count: "Low Character Count",
    high_character_count: "High Character Count",
    low_readability_rate: "Low Readability Rate",
    irrelevant_title: "Irrelevant Title",
    deprecated_html_tags: "Deprecated HTML Tags",
    duplicate_title_tag: "Duplicate Title Tags",
    no_title: "No Title",
    flash: "Flash Content",
    lorem_ipsum: "Lorem Ipsum Content",
    has_misspelling: "Has Misspellings",
    canonical_to_broken: "Canonical to Broken",
    canonical_to_redirect: "Canonical to Redirect",
    has_links_to_redirects: "Has Links to Redirects",
    is_orphan_page: "Is an Orphan Page",
    has_meta_refresh_redirect: "Has Meta Refresh Redirect",
    meta_charset_consistency: "Meta Charset Consistency",
    size_greater_than_3mb: "Size Greater Than 3MB",
    has_html_doctype: "Has HTML Document Type (DOCTYPE)",
    https_to_http_links: "HTTPS to HTTP Links",
    has_render_blocking_resources: "Has Render-Blocking Resources",
    redirect_chain: "Redirect Chain",
    canonical_chain: "Canonical Chain",
    is_link_relation_conflict: "Is Link Relation Conflict",
    api: "API",
    function: "Function",
    url: "URL",
    target: "Target",
    load_resources: "Load Resources",
    crawl_status: "Crawl Status",
    items_count: "Items Count",
    items: "Items",
    page_url: "Page URL",
    time_to_interactive: "Time to Interactive",
    dom_complete: "DOM Complete",
    connection_time: "Connection Time",
    time_to_secure_connection: "Time to Secure Connection",
    request_sent_time: "Request Sent Time",
    waiting_time: "Waiting Time",
    download_time: "Download Time",
    duration_time: "Duration Time",
    fetch_start: "Fetch Start",
    fetch_end: "Fetch End",
    resources: "Resources",
    initiator: "Initiator",
    location: "Location",
    is_render_blocking: "Is Render Blocking",
  };
  

  const translations = {...originalMapping}
  Object.keys(translations).map((key) => {

    let value = translations[key];
    translations[key] = {
      title: value,
      isCheck: (key.startsWith('is') ? true : false)
    }
  })

  export const titleMapping = translations